apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack_webhook: ""
    notifications.argoproj.io/subscribe.on-sync-failed.slack_webhook: ""
    notifications.argoproj.io/subscribe.on-health-degraded.slack_webhook: ""
spec:
  destination:
    namespace: project
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: wordpress
    repoURL: https://igortank.github.io/study-project/
    targetRevision: 1.1.6
    helm:
      parameters:
        - name: image.tag
          value: v1.0.6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
