apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.app-deployed: ""
    notifications.argoproj.io/subscribe.on-sync-failed.app-sync-failed: ""
    notifications.argoproj.io/subscribe.on-health-degraded.app-health-degraded: ""
spec:
  destination:
    namespace: project
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: wordpress
    repoURL: https://igortank.github.io/study-project/
    targetRevision: 1.0.7
    helm:
      parameters:
        - name: image.tag
          value: v1.0.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
