---
apiVersion: v1
kind: Namespace
metadata:
  name: project

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-wordpress
provisioner: cluster.local/nfs-nfs-subdir-external-provisioner
parameters:
  onDelete: "retain"
  pathPattern: "/IgorBudarkevich/wordpress/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app01-pv-claim-app
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-wordpress
  resources:
    requests:
      storage: 3Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: budarkevichigor/wordpress:1.0.2
        env:
        - name: WORDPRESS_DB_HOST
          value: "192.168.201.2:3306"
        - name: WORDPRESS_DB_USER
          value: "db_admin"
        - name: WORDPRESS_DB_PASSWORD
          value: "db_admin"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 400Mi
          limits:
            cpu: 1000m
            memory: 1500Mi
        volumeMounts:
        - name: persistent-storage-app
          mountPath: /var/www/html/wp-content/
          subPath: wp-content
      volumes:
      - name: persistent-storage-app
        persistentVolumeClaim:
          claimName: app01-pv-claim-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wordpress
  namespace: project
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: wordpress.k8s-2.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-svc
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: project
  labels:
    run: wordpress-svc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wordpress
