---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  accessModes:
      - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  storageClassName: nfs-{{ .Chart.Name }}