apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  strategy:
    {{- if .Values.deployStrategy.blueGreenEnable -}}
    blueGreen:
      activeService: {{ template "wordpress.fullname" . }}
      previewService: {{ template "wordpress.fullname" . }}-preview
      autoPromotionEnabled: {{ .Values.deployStrategy.autoPromotionEnabled }}
      autoPromotionSeconds: {{ .Values.deployStrategy.autoPromotionSeconds }}
      previewReplicaCount: {{ .Values.deployStrategy.previewReplicaCount }}
      scaleDownDelaySeconds: {{ .Values.deployStrategy.scaleDownDelaySeconds }}
    {{- else }}
    canary:
      canaryService: {{ template "wordpress.fullname" . }}-preview
      stableService: {{ template "wordpress.fullname" . }}
      trafficRouting:
        nginx:
          stableIngress: {{ template "wordpress.fullname" . }}
          additionalIngressAnnotations:
            affinity: "cookie"
            session-cookie-name: "route"
            session-cookie-max-age: "172800"
      steps:
      - setWeight: 25
      - pause: {duration: {{ .Values.deployStrategy.pauseDuration }}}
      - setWeight: 50
      - pause: {}
    {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wordpress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: WORDPRESS_DB_HOST
            value: {{ .Values.env.DBHOST }}
          - name: WORDPRESS_DB_USER
            value: {{ .Values.env.DBUSER }}
          - name: WORDPRESS_DB_PASSWORD
            value: {{ .Values.env.DBPASSWORD }}
          - name: WORDPRESS_DB_NAME
            value: {{ .Values.env.DBNAME }}
          volumeMounts:
          - name: {{ .Chart.Name }}-pvc-app
            mountPath: {{ .Values.mnt.mountPath }}
            subPath: {{ .Values.mnt.subPath }}
      volumes:
      - name: {{ .Chart.Name }}-pvc-app
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-pvc
